name: cypress_shop_project

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser:
          - chrome
          - electron
        test_suite:
          - login
          - registration
          - shopping_cart

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run test:${{ matrix.test_suite }}:${{ matrix.browser }}

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Mochawesome HTML Report
          path: mochawesome-report

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          


          
