name: cypress_shop_project

on: push

jobs:
  ui-regression:
    name: Cypress UI Regression Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression
          record: true

      - name: Upload Cypress Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          #SLACK_USERNAME: Vladyslav Savchuk
          #SLACK_TITLE: Regression Test
          #SLACK_MESSAGE: "Slack notification: test result: ${{ job.status }}"
          #SLACK_COLOR: ${{ job.status }}

          




          
