name: cypress_shop_project

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 */5 * * *'  # Runs every 5 hours (0 */5 * * *)

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run with Chrome
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression:chrome
          record: true

      - name: Uploading artifact (Chrome)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report-chrome
          path: cypress/reports/html
          retention-days: 30

      - name: Cypress run with Electron
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression:electron
          record: true

      - name: Uploading artifact (Electron)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report-electron
          path: cypress/reports/html
          retention-days: 30
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
  
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Vladyslav Savchuk
          SLACK_TITLE: Regression Test
          SLACK_MESSAGE: "Slack notification:test result:${{ job.status }}"
          SLACK_COLOR: ${{ job.status }}
